test - remove patient care node_modules dir?
So the docker build for patient care is cryptically erroring
(see below)
with the EXDEV type errors we've seen before.
Since we do run npm install as part of the build process,
i think in theory we can just install rimraf again from scratch
and it may work.

not confident.

npm WARN patient-care@ No description
npm WARN patient-care@ No repository field.
npm WARN patient-care@ No license field.
npm ERR! Linux 3.19.0-66-generic
npm ERR! argv "node" "/root/.meteor/packages/meteor-tool/1.3.5_1/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! path /app/node_modules/rimraf
npm ERR! code EXDEV
npm ERR! errno 52
npm ERR! EXDEV, rename '/app/node_modules/rimraf'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
ERROR: Service 'patient-care' failed to build: The command '/bin/sh -c meteor npm install' returned a non-zero code: 52