require byLine appropriate to its use as function
Previous version, jobs would get rejected with following message:
job: rejected -  [TypeError: Property 'byLine' of object [object Object] is not a function]

Not sure if this allows it to be used outside of globals.js but right now it's not.